<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="MSTest" Version="4.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CardManager\CardManager.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="TestData\DefaultCards.json" />
      <None Remove="TestData\DefaultLevelCurve.json" />
      <Content Include="TestData\DefaultLevelCurve.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="TestData\DefaultCardDefinitions.json" />
      <Content Include="TestData\DefaultCardDefinitions.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="TestData\DefaultStatCurves.json" />
      <Content Include="TestData\DefaultStatCurves.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
